const ES_ON=/^\/es(\/|$)/.test(location.pathname);
let LANG=ES_ON?"es":"en";
const SL={photo:"fotos",film:"video",contact:"contacto",blog:"blog"},SR=Object.fromEntries(Object.entries(SL).map(a=>[a[1],a[0]]));
const L=p=>{if(LANG!=="es")return p;const g=p.split("/").filter(Boolean);if(g.length===1&&SL[g[0]])g[0]=SL[g[0]];return "/es/"+g.join("/")+(g.length?"/":"")};
const OTHER=(()=>{let h=location.pathname.replace(/^\/|\/$/g,"").replace(/\.html$/,"");if(LANG==="es"){h=h.replace(/^es\/?/,"");h=SR[h]||h;return "/"+h+(h?"/":"")}return h===""?"/es/":SL[h]?"/es/"+SL[h]+"/":"/es/"+(h.startsWith("blog/")?"blog/":"")})();
const PES=[["Los mejores confeti para fotos y videos de boda espectaculares","El lanzamiento de confeti es uno de los momentos más alegres y visuales de una boda. Es una oportunidad para capturar emociones auténticas."],["El arte del velo: elegancia atemporal para el día de tu boda","Pocos accesorios nupciales igualan el encanto atemporal del velo: aportan elegancia, romance y dramatismo a cada momento capturado."],["Bodas de lujo: la planificación, la perfección y dónde encaja El Salvador Weddings","Detrás de cada boda de lujo hay un camino que empieza meses, a veces años, antes del gran día."],["¿Te cuesta elegir el lugar de tu boda? 5 espectaculares lugares del Reino Unido favoritos de El Salvador Weddings","A la hora de planificar la boda de tus sueños, el lugar no es solo un fondo: marca el tono de todo el día."],["Celebrando historias de amor multiculturales con El Salvador Weddings","Capturamos momentos sinceros con cuidado, celebrando la mezcla única de culturas y tradiciones de cada boda."],["¿Sueñas con una boda en un castillo? Así capturamos la magia en Pennsylvania Castle Estate","¿Sueñas con una boda en un castillo junto al mar? Pennsylvania Castle Estate, en la costa de Dorset, es un lugar sin igual."],["Por qué El Salvador Weddings está llamado a ser la primera opción en fotografía y cinematografía de bodas de lujo","En las bodas de lujo, las parejas saben lo importante que es crear una experiencia inolvidable."],["Por qué contratar a un fotógrafo y un videógrafo que ya trabajan juntos","En todos mis años de experiencia, y por colegas de la profesión, he oído y visto muchas historias."],["Necesitas un videógrafo de bodas mucho más de lo que crees","Tener un video de boda es cada vez más importante: permite revivir el momento."],["Momentos emotivos: películas de boda personalizadas","El amor es un hermoso viaje lleno de momentos emotivos que merecen ser capturados y atesorados toda la vida."],["Elegancia al descubierto: espectaculares muestras de bodas","Al planificar una boda de lujo, capturar los momentos especiales es esencial para inmortalizar el día."],["Capturando el amor: cinematografía de bodas de lujo","Para capturar la esencia del amor en tu día especial, nada mejor que un servicio de cinematografía de bodas de lujo."]];
const TT=p=>LANG==="es"&&PES[POSTS.indexOf(p)]?PES[POSTS.indexOf(p)]:[p[1],p[6]];

const SITE="https://davidrinconjimenez.wixsite.com/firecrackerweddings";
const HERO="329158_c646c106a0954dbb9968b6c729aa6d0ef000.jpg";
const PH=["55ec88_f0012407b07943c79c6137a888317eed","55ec88_4a4dc1e99bca43c59eeebad05d23c0de","55ec88_39388a970ec74a89b9ef5f5beb2cbeee","55ec88_0eebf036a9154178bda4762cc24a18ff","55ec88_cb43f7e75f944075b0ef09105eaf16cf","55ec88_bc6b32c400b34be893f6492c839c469c","55ec88_49f1172df05a4d0ba0d2c7590b195448","55ec88_3196f3ac71dc4a319e9886f0366b1553","55ec88_92cf3b7bec5941ccb6cbac4bdda9d43d","55ec88_a609d66d0ef34147b5cfde9cfceab14f","55ec88_2f675e086b20416190bcbf7b5bc76c9c","55ec88_b73f3674ca8b42ecb75faad82076db66","55ec88_71de70608112442a9a1d61faa1093431","55ec88_e762090a1027443c8dae233f98768d8c","55ec88_2ba3172b72c748eeadd0fc0577e8cff7","55ec88_91dba7213b17457386b778631d3e8be5","55ec88_0d9528ede7cc4a73988ab55258b4f615","55ec88_c69b65acb34646b19db1b697060f081d","55ec88_4ad55f1363f24318b2b4c83d919015ab","55ec88_90c7ce1b012b4f24b59de43d90d9284f","55ec88_29e5193d241a4463bfada002ca4c09ef","329158_880f7b1f29214d85a13e62f68887c6fb"].map(x=>x+"~mv2.jpg");
const TAGS="Insta: weddingvideographeruk\n\n#weddingvideography\n#weddingvideo\n#londonvideographer";
const VID=[
["ARpPdgYCyaY","Pennsylvania Castle - Cinematic wedding - London videographer Sony A7SIII","sddefault","14:47",`I had the pleasure of filming this beautiful wedding in Dorset, the venue was amazing and the staff, everything so well organized, a castle with so much history.

Copied from their website:

Historical castle by the sea
This luxurious 18th-century castle is located on the Jurassic coastline and is available for exclusive use, ideal for self-catered holidays, big party weekends, corporate retreats and celebrations. Following a refurbishment, Pennsylvania Castle offers classic yet modern surroundings with a distinct focus on comfort and luxury, featuring nine immaculate en-suite bedrooms, extensive entertainment and living areas and an indoor pool. Within the castle grounds are five luxury clifftop lodges, offering accommodation for another 20 guests and stunning coastal views.

Pennsylvania Castle was opened by Princess Elizabeth, daughter of King George III, in 1800 and since then has enjoyed a rich and varied history that takes in Royal celebrations - the King and Queen visited in 1800 and enjoyed their wedding anniversary there, the Napoleonic Wars, preparations for the D Day landings, and literary figures such as Thomas Hardy. In 1950 the castle was turned into a hotel, then back into a private home in 1994 and is once again open to the public for private hire.

The castle and its grounds occupy a total of 1.73 hectares (4.27 acres), with gardens that have been impeccably designed to provide secluded retreats throughout, adding to the charm and privacy of the estate. With beautiful reception rooms, elegant en-suites and stunning grounds you are sure to enjoy a luxury escape by the sea here.

`+TAGS],
["pscv_IfkeNw","Ashridge House Wedding - Cinematic wedding - London videographer","maxresdefault","09:05",`Absolutely stunning wedding at ashridgehouse.org.uk

Once a royal residence to King Henry VIII and Princess Elizabeth I, today Ashridge House is an award winning meeting, events, and wedding venue. Set in 190 acres of beautiful landscaped gardens, Ashridge House is located in Hertfordshire, only 30 minutes north of London.

Ashridge House is the perfect environment to learn, reflect and to be inspired. Step back into history and elegance in our luxury Grade I neo-gothic country house; we welcome you to join us and be part of Ashridge House history.

I hope you enjoy it.

`+TAGS],
["vEtHxNTmiNA","Wedding video - Boclair House Glasgow - Fun cinematic wedding film - A7SIII London videographer","maxresdefault","10:54",`What a fun and beautiful wedding with Yi and Datong in Glasgow, a stunning venue with a lot of spots to create stunning images.

I hope you enjoy it.

`+TAGS+`\n#weddingfilm`],
["SUFFDEudcBw","Wedding film Italian villa Bournemouth - wedding highlights - wedding videographer - Sony A7SIII","maxresdefault","16:58",`I had the chance to film in this epic wedding venue in Bournemouth, near the seaside.

I hope you enjoy it.

`+TAGS+`\n#weddinginspiration`],
["QiYF1tE_2qc","Wedding film Leipzig Germany - London wedding videographer","maxresdefault","13:45",`I was so honored to be asked to travel all the way to Leipzig in Germany to film this wedding, really grateful to all the couples that appreciate my work so much and feel that my work and style is somehow unique and worth it to do the extra effort to get me to the destination.

All I can say is thank you so much :)

I hope you enjoy it.

`+TAGS+`\n#weddingfilm`],
["fEOe8Gi2hF4","Wedding video Highcliffe Castle and The Nici Bournemouth - Fun cinematic wedding film","maxresdefault","10:20",`I hope you enjoy it.

`+TAGS+`\n#weddingfilm`],
["vPqQvtEO_MI","Wedding film Amsterdam - Wedding videography - Sony A7SIII","hqdefault","09:00",`A gorgeous wedding in Amsterdam with a lovely couple, one of my favorite weddings this year, enjoyed very much filming around the canals and beautiful streets.

I hope you enjoy this wedding film.

`+TAGS+`\n#weddinginspiration\n#weddingideas\n#weddingdestination`]
];
const F=id=>id.includes(".")?id:id+"~mv2.jpg";
const G={
A:[["55ec88_f0012407b07943c79c6137a888317eed","A wedding couple in Kensington walking together in a nearby mews"],["55ec88_4a4dc1e99bca43c59eeebad05d23c0de","Our couple in front of the beautiful Ashridge House in Berkhampsted"],["55ec88_39388a970ec74a89b9ef5f5beb2cbeee","A beautiful moment with a couple embracing at Crondon Park Golf Club in Essex"],["55ec88_0eebf036a9154178bda4762cc24a18ff","A closeup of our couple at Ashridge House"],["55ec88_cb43f7e75f944075b0ef09105eaf16cf","A casual image of a couple walking in the vineyard at Old Luxters Barn in Henley"],["55ec88_bc6b32c400b34be893f6492c839c469c","A wedding couple dancing in a barn"]],
B:[["images/emo-1.jpg","Bride laughing with her groom in golden sunset light"],["images/emo-2.jpg","Bride and groom at sunset by the sea with her veil flying in the wind"],["55ec88_92cf3b7bec5941ccb6cbac4bdda9d43d","DSC09874"],["images/emo-3.jpg","Bride cheering with a putter during a garden wedding"],["55ec88_2f675e086b20416190bcbf7b5bc76c9c","1MS04792"],["55ec88_b73f3674ca8b42ecb75faad82076db66","1MS04880"]],
C:[["329158_ea5df86436bd4ed4b4c83e7a731f42d9~mv2.png","vlcsnap-2024-07-02-20h06m31s919"],["329158_10fc25661d184122a141c25e893e6dc9","Still 2024-08-07 141755_3.1.1"],["329158_49f19c1b02a94ff3971bbe5d5ca8a4be","DSC01194"],["55ec88_91dba7213b17457386b778631d3e8be5","1MS08398"],["55ec88_0d9528ede7cc4a73988ab55258b4f615","2MS06604"],["55ec88_4ad55f1363f24318b2b4c83d919015ab","DRJ02470"]]
};
const WY=[["Unlimited Full-Day Wedding Coverage","We capture every moment without time constraints."],["Seamless Photo &amp; Film Collaboration","Hybrid team ensures a cohesive visual story."],["Customized Style","Tailored to match your unique vision and preferences."],["High-Resolution Digital Gallery","Easily share, download, and print your photos."],["Expert Guidance","Support before and during your wedding for perfect shots."],["Exclusive Wedding Tips PDF","Includes top advice for a flawless wedding day."],["Drone Footage Included","Aerial views, weather permitting, for a cinematic touch."],["Multicultural Wedding Expertise","Experienced in honoring diverse cultural traditions."],["Cinematic Wedding Video","Professionally edited, high-definition video capturing all the key moments."]];
const AR={A:[1.5,1.5,1.5,.667,1.5,1.5],B:[1.5,1,.667,1.5,1.5,1.5],C:[1.778,1.778,.667,1,.667,1.5]};
const PG=k=>`<div class="pg">${G[k].map((x,i)=>`<button data-g="${k}" data-i="${i}" title="Press to zoom"><img loading="lazy" src="${img(F(x[0]),600)}" alt="${x[1]}"></button>`).join("")}</div>`;
const SS=k=>`<div class="gg">${G[k].map((x,i)=>`<button data-g="${k}" data-i="${i}" title="Press to zoom" style="flex:${AR[k][i]} 1 ${Math.round(AR[k][i]*210)}px;aspect-ratio:${AR[k][i]}"><img loading="lazy" src="${img(F(x[0]),900)}" alt="${x[1]}"></button>`).join("")}</div>`;
// BODY: full article HTML goes in `body` (paragraphs, <h2>, <img>). If empty, the page links to the original post.
const POSTS=[
["the-best-confetti-for-stunning-wedding-photos-videos","The Best Confetti for Stunning Wedding Photos & Videos","Mar 23, 2025","Martin Sylvester","5 min","55ec88_0d8cc904a5164940b1c4e36d9bbd5495~mv2.jpg","A confetti toss is one of the most joyful and visually striking moments in a wedding. It’s a chance to capture authentic emotions.",""],
["the-art-of-the-veil-adding-timeless-elegance-to-your-wedding-day","The Art of the Veil: Adding Timeless Elegance to Your Wedding Day","Dec 2, 2024","Martin Sylvester","3 min","55ec88_656cbb539a7b487fa1f8bdd4443036c5~mv2.jpg","Few bridal accessories match the timeless charm of the wedding veil - adding elegance, romance, and drama to every captured moment.",""],
["luxury-weddings-the-planning-the-perfection-and-how-firecracker-weddings-fits-in","Luxury Weddings: The Planning, the Perfection, and How El Salvador Weddings Fits In","Nov 25, 2024","Martin Sylvester","2 min","329158_f25129ef1a2c4a419753666a42ebc77f~mv2.jpg","Behind every luxury wedding is a journey that starts months—sometimes years—before the big day.",""],
["5-stunning-uk-wedding-venues","Struggling to Choose Your Wedding Venue? Here Are 5 Stunning UK Wedding Venues Loved by El Salvador Weddings","Nov 24, 2024","Martin Sylvester","2 min","329158_92dd822e4a134ee198f008099bb30285~mv2.jpg","When it comes to planning your dream wedding, the venue isn’t just a backdrop—it sets the tone for the entire day.",""],
["celebrating-multicultural-love-stories-with-firecracker-weddings","Celebrating Multicultural Love Stories with El Salvador Weddings","Nov 23, 2024","Martin Sylvester","3 min","55ec88_654567519eaa4bb593756befb8d0a229~mv2.jpg","El Salvador Weddings captures heartfelt moments with care, celebrating the unique blend of cultures and traditions in every wedding.",""],
["dreaming-of-a-castle-wedding-here-s-how-firecracker-weddings-captured-the-magic-at-pennsylvania-cas","Dreaming of a Castle Wedding? Here’s How El Salvador Weddings Captured the Magic at Pennsylvania Castle Estate","Nov 22, 2024","Martin Sylvester","2 min","55ec88_4c4f18c65a2b4a8c81245a862ddf0c12~mv2.jpg","Dreaming of a wedding in a stunning coastal castle? Pennsylvania Castle Estate on the Dorset coastline is a venue like no other.",""],
["why-firecracker-weddings-is-poised-to-become-the-uk-s-premier-choice-for-luxury-wedding-photography","Why El Salvador Weddings is Poised to Become the UK’s Premier Choice for Luxury Wedding Photography and Cinematography","Nov 11, 2024","Martin Sylvester","4 min","55ec88_f5d87e965086424397b53a9062653d2e~mv2.jpg","When it comes to luxury weddings, couples understand the importance of creating an unforgettable experience.",""],
["why-you-need-to-hire-for-your-wedding-a-photographer-and-videographer-that-already-work-together","Why you need to hire for your wedding a photographer and videographer that already work together","Sep 5, 2024","David RJ","1 min","329158_33e5f37bcc084cafac0f31873ec17008~mv2.png","In all my years of experience and from other colleagues in the profession, I have heard and seen a lot of stories.",""],
["you-need-a-wedding-videographer-way-more-than-you-think","You need a wedding videographer way more than you think","Sep 5, 2024","David RJ","2 min","329158_ad522bb7f3ae42859edf21a7dbcd8792~mv2.jpg","Getting a wedding video has become increasingly more important, being able to revive the moment.",""],
["emotional-moments-personalized-wedding-films","Emotional Moments: Personalized Wedding Films","Jul 9, 2024","David RJ","2 min","329158_b198b894d9c9440785d94787fb2c9b16~mv2.png","Love is a beautiful journey filled with emotional moments that deserve to be captured and cherished for a lifetime.",""],
["unveiling-elegance-stunning-wedding-showcases","Unveiling Elegance: Stunning Wedding Showcases","Jul 9, 2024","David RJ","1 min","329158_3438763162bd4369bede55a0975bffda~mv2.png","When it comes to planning a luxury wedding, capturing those special moments is an essential part of immortalizing the day.",""],
["capturing-love-luxury-wedding-cinematography","Capturing Love: Luxury Wedding Cinematography","Jul 9, 2024","David RJ","2 min","329158_b3ffe786f4504b3eb683fedd1f801499~mv2.png","When it comes to capturing the essence of love on your special day, look no further than a luxury wedding cinematography service.",""]
];
const $=s=>document.querySelector(s),app=$("#app");
const img=(f,w)=>f.startsWith("images/")?"/"+f:`https://static.wixstatic.com/media/${f}/v1/fit/w_${w},h_${w},q_80/${f}`;
const NAV=[["","Home"],["photo","Photo"],["film","Film"],["contact","Contact"],["blog","Blog"]];
$("#nav").innerHTML=NAV.map(n=>`<a href="${L("/"+n[0]+(n[0]?"/":""))}" data-k="${n[0]}">${n[1]}</a>`).join("");
const vcards=()=>`<div class="grid">${VID.map(v=>`<button class="v" data-y="${v[0]}"><div class="t"><img loading="lazy" src="https://i.ytimg.com/vi/${v[0]}/${v[2]}.jpg" alt=""></div><b>${v[1]}</b></button>`).join("")}</div>`;
const pcards=l=>`<div class="grid">${l.map(p=>`<a class="card" href="/blog/${p[0]}/"><img loading="lazy" src="${img(p[5],700)}" alt=""><h3>${TT(p)[0]}</h3><p class="meta">${p[3]} · ${p[2]} · ${p[4]} ${LANG==="es"?"de lectura":"read"}</p><p>${TT(p)[1]}</p></a>`).join("")}</div>`;
const form=()=>`<form id="fm" class="cf"><h2 class="gi">Get in touch</h2><div class="r2"><label>First name *<input required name="a"></label><label>Last name<input name="b"></label></div><div class="r2"><label>Email *<input required type="email" name="e"></label><label>Phone *<input required type="tel" name="p"></label></div><label>Wedding Venue &amp; Location *<input required name="v"></label><label>Wedding Date *<div class="r3"><input required type="number" min="1" max="31" name="dd" placeholder="Day"><select required name="dm"><option value="">Month</option>${Array.from({length:12},(_,i)=>`<option value="${i+1}">${new Date(2000,i,1).toLocaleString(LANG==="es"?"es":"en",{month:"long"})}</option>`).join("")}</select><input required type="number" min="2026" max="2035" name="dy" placeholder="Year"></div></label><label>What service are you interested in?<select name="s"><option value="">Choose one</option><option>Photography &amp; Film</option><option>Photography</option><option>Film</option></select></label><label>How did you find about us? *<input required name="h"></label><label>Write a message<textarea name="m" rows="5"></textarea></label><button class="btn sub">Submit</button></form>`;
const PAGES={
"":()=>`<div class="vp"><iframe src="https://www.youtube-nocookie.com/embed/5XhSu4Jej8c?autoplay=1&mute=1&loop=1&playlist=5XhSu4Jej8c&rel=0&playsinline=1&modestbranding=1" title="Luxury Wedding Showreel" allow="autoplay; fullscreen; picture-in-picture; encrypted-media" allowfullscreen></iframe></div><div class="ht"><h1>El Salvador Weddings</h1><p class="tag">European-style luxury wedding photography &amp; films in El Salvador</p></div>
<section><div class="w two"><img loading="lazy" src="${img(PH[21],900)}" alt=""><div><h2>OUR JOURNEY</h2><p>Embark on a visual journey with us as we capture the essence of love and emotions. Each project is a unique experience, reflecting the beauty of relationships and special moments. Explore our work and feel the love in motion.</p><p>Our team is more like a family of passionate artists &amp; adventurers. We have had the pleasure of documenting over 300 love stories from around the globe.</p><p>We can't wait to capture the magic of your special day! Share your exciting plans with us using the form below, and let's start creating unforgettable memories together.</p></div></div></section>
<section class="wf"><div class="wfl" style="background-image:linear-gradient(#000a,#000d),url(${img(F("55ec88_71de70608112442a9a1d61faa1093431"),1400)})"><h2>Why Us</h2>${WY.map(w=>`<div class="li">• <b>${w[0]}:</b> ${w[1]}</div>`).join("")}</div><div class="wfr">${form()}</div></section>
<section><div class="w">${pcards(POSTS.slice(0,3))}</div></section>`,
photo:()=>`<div class="dk"><div class="hr"><img src="${img(F("55ec88_e762090a1027443c8dae233f98768d8c"),1800)}" alt=""></div>
<div class="intro"><h2 class="it">PHOTOGRAPHY PORTFOLIO</h2><p>Our luxury wedding photography portfolio showcases the epitome of elegance and sophistication, capturing timeless moments with exquisite detail.</p><p>We specialize in creating stunning visual narratives that reflect the grandeur and emotion of your special day. Each photograph is a blend of artistic vision and meticulous craftsmanship, ensuring your memories are preserved with unparalleled beauty and style. Let us tell your love story through images that resonate with romance and luxury.</p></div>
<div class="band"><div class="in">${PG("A")}<div class="tx"><h6>RELAXED:</h6><p>Embracing a relaxed approach to wedding photography enhances the luxury experience, capturing moments with an effortless elegance. By fostering a calm, laid-back atmosphere, our photographer allows couples to naturally enjoy their day, resulting in authentic, candid shots.</p><p>This stress-free method not only showcases the true essence of the celebration but also adds a touch of sophistication, ensuring each photo tells a heartfelt story.</p><p>This blend of relaxed photography creates timeless images, preserving precious memories with grace and style, ultimately reflecting the luxurious ambiance of your wedding day.</p></div></div></div>
<div class="band"><div class="in"><div class="tx"><h6 style="font-size:1.15rem">EMOTIONAL STORY-TELLING:</h6><p>An emotional storytelling approach in wedding photography weaves a powerful narrative, capturing the heartfelt moments that define the day. By focusing on genuine expressions and intimate interactions, the photographer brings out the emotions that make each wedding unique.</p><p>This method goes beyond posed shots, embracing the spontaneous and the candid to tell a compelling love story.</p><p>Combining modern contemporary techniques with a keen eye for detail, the result is a collection of images that are both visually stunning and deeply moving. Each photograph becomes a cherished memory, reflecting the true essence of the couple's journey and the emotions shared with loved ones.</p></div>${PG("B")}</div></div>
<div class="fl"><h2>FILM INSPIRATION</h2><div class="fi"><img loading="lazy" src="${img(F("55ec88_71de70608112442a9a1d61faa1093431"),900)}" style="object-position:52% 39%" alt=""><img loading="lazy" src="${img(F("55ec88_dc77adc47d53429fa0e808cc78971569"),900)}" style="object-position:48% 51%" alt=""><img loading="lazy" src="${img(F("329158_bcc581d16d0d4dc7998fc35e83a174ce"),900)}" style="object-position:63% 58%" alt=""></div></div>
<div class="band" style="margin-top:0"><div class="in"><div class="sl">${PG("C")}<button class="ar" data-d="-1" aria-label="Previous">‹</button><button class="ar r" data-d="1" aria-label="Next">›</button></div><div class="tx"><h6 class="s">ARTISTIC VISION</h6><p>Drawing on the world of haute couture, our approach emphasizes dramatic compositions, and meticulous attention to detail.</p><p>Our photographer utilizes fashion-forward techniques, playing with light, shadow, and innovative angles to create visually stunning images that exude glamour.</p><p>This style transforms each moment into a magazine-worthy shot, capturing the couple and their guests in their most glamorous and sophisticated states.</p><p>The result is a luxurious, artful collection of photographs that not only document the wedding day but also celebrate it as a stylish, timeless event.</p></div></div></div></div>`,
film:()=>`<div class="fh" style="background-image:url(${img(F("55ec88_63b0c8b32de5400294173cc952b59b6d"),1800)})"><h1>Films</h1></div>
<div class="av"><i>⋮</i><b>All Videos</b></div>
<div class="vs"><div class="tr">${VID.map(v=>`<div class="vc"><button class="t" data-y="${v[0]}" aria-label="Play Video"><img loading="lazy" src="https://i.ytimg.com/vi/${v[0]}/${v[2]}.jpg" alt="${v[1]}"><span class="du">${v[3]}</span></button><h3>${v[1]}</h3><p>${(v[1]+" "+v[4]).replace(/\s+/g," ")}</p></div>`).join("")}</div><button class="ar" data-d="-1" aria-label="Previous">‹</button><button class="ar r" data-d="1" aria-label="Next">›</button></div>
<div class="wy"><div class="l"><h2>Why Us</h2>${WY.map(w=>`<div class="li">• <b>${w[0]}:</b> ${w[1]}</div>`).join("")}<a class="btn" href="mailto:hi@davidrj.com?subject=Luxury%20wedding%20enquiry">Get in touch</a></div><img loading="lazy" src="${img(F("329158_45993666e11840d9b5efb52e301129b0~mv2.png"),1400)}" alt=""></div>`,
contact:()=>`<section><div class="w" style="max-width:760px"><h2>Get in touch</h2><p class="meta">+44 (0)754935 8836 · El Salvador &amp; London</p>${form()}</div></section>`,
blog:()=>`<section><div class="w"><h2>Blog</h2>${pcards(POSTS)}</div></section>`
};
function post(slug){const p=POSTS.find(x=>x[0]===slug);if(!p)return PAGES[""]();
 const i=POSTS.indexOf(p),nx=POSTS[i+1];
 return `<section><article class="post"><a class="meta" href="${L("/blog/")}">← All posts</a><h1>${p[1]}</h1><p class="meta">${p[3]} · ${p[2]} · ${p[4]} read</p><img src="${img(p[5],1400)}" alt="">${p[7]||`<p>${p[6]}</p><p><a class="btn" href="${SITE}/post/${p[0]}" target="_blank" rel="noopener">Read the full article</a></p>`}<p style="margin-top:30px"><a class="btn" href="${L("/contact/")}">Get in touch today</a></p>${nx?`<p class="meta" style="margin-top:30px">Next: <a href="/blog/${nx[0]}/" style="color:var(--acc)">${nx[1]}</a></p>`:""}</article></section>`}
const lb=$("#lb"),lc=$("#lc");let idx=0,LB=[];
const arr=on=>$("#lp").style.display=$("#ln").style.display=on?"":"none";
const show=()=>lc.innerHTML=`<img src="${img(LB[idx],2000)}" alt="">`;
const step=d=>{idx=(idx+d+LB.length)%LB.length;show()};
const close=()=>{lb.classList.remove("on");lc.innerHTML=""};
$("#lx").onclick=close;$("#lp").onclick=()=>step(-1);$("#ln").onclick=()=>step(1);lb.onclick=e=>{if(e.target===lb)close()};
addEventListener("keydown",e=>{if(!lb.classList.contains("on"))return;if(e.key==="Escape")close();if(e.key==="ArrowLeft")step(-1);if(e.key==="ArrowRight")step(1)});
function route(){let h=location.pathname.replace(/^\/|\/$/g,"").replace(/\.html$/,"");if(LANG==="es"){h=h.replace(/^es\/?/,"");h=SR[h]||h}const m=LANG==="es"?null:h.match(/^blog\/(.+)/),k=m?"blog":h.split("/")[0];
 app.innerHTML=m?post(m[1]):(PAGES[k]||PAGES[""])();
 document.querySelectorAll("#nav a").forEach(a=>a.classList.toggle("on",a.dataset.k===(PAGES[k]||m?k:"")));
 app.querySelectorAll(".vc .t").forEach(b=>b.onclick=()=>{lc.innerHTML=`<div class="fr"><iframe src="https://www.youtube-nocookie.com/embed/${b.dataset.y}?autoplay=1&rel=0" allow="autoplay; fullscreen" allowfullscreen></iframe></div>`;arr(0);lb.classList.add("on")});
 app.querySelectorAll(".vs .ar").forEach(b=>b.onclick=()=>{const g=b.parentNode.querySelector(".tr");g.scrollBy({left:+b.dataset.d*g.clientWidth*.49,behavior:"smooth"})});
 app.querySelectorAll(".pg button").forEach(b=>b.onclick=()=>{LB=G[b.dataset.g].map(x=>F(x[0]));idx=+b.dataset.i;show();arr(1);lb.classList.add("on")});
 app.querySelectorAll(".sl .ar").forEach(b=>b.onclick=()=>{const g=b.parentNode.querySelector(".pg");g.scrollBy({left:+b.dataset.d*g.clientWidth*.45,behavior:"smooth"})});
 const f=$("#fm");if(f)f.onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f));const NM={a:"First name",b:"Last name",e:"Email",p:"Phone",v:"Venue & location",dd:"Day",dm:"Month",dy:"Year",s:"Service",h:"How they found us",m:"Message"};location.href=`mailto:hi@davidrj.com?subject=${encodeURIComponent("Wedding enquiry "+[d.dd,d.dm,d.dy].join("/"))}&body=${encodeURIComponent(Object.entries(d).map(x=>(NM[x[0]]||x[0])+": "+x[1]).join("\n"))}`};
 tr(app);scrollTo(0,0)}

const ES={"Home":"Inicio","Photo":"Fotos","Film":"Video","Contact":"Contacto","Blog":"Blog","50% off":"50% de descuento","on Weddings in El Salvador":"en bodas en El Salvador, para reservas hechas hasta noviembre de 2027 ·","Book your date":"Reserva tu fecha","European-style luxury":"Fotografía y películas de boda de lujo, al estilo europeo, en El Salvador","OUR JOURNEY":"NUESTRA HISTORIA","Embark on a visual journey":"Embárcate en un viaje visual con nosotros mientras capturamos la esencia del amor y las emociones. Cada proyecto es una experiencia única que refleja la belleza de las relaciones y los momentos especiales. Explora nuestro trabajo y siente el amor en movimiento.","Our team is more like":"Nuestro equipo es más como una familia de artistas y aventureros apasionados. Hemos tenido el placer de documentar más de 300 historias de amor de todo el mundo.","We can't wait to capture":"¡Estamos deseando capturar la magia de tu día especial! Cuéntanos tus planes con el formulario y comencemos a crear recuerdos inolvidables juntos.","Why Us":"Por qué elegirnos",
"Unlimited Full-Day Wedding Coverage:":"Cobertura ilimitada de todo el día:","We capture every moment":"Capturamos cada momento sin límites de tiempo.","Seamless Photo & Film Collaboration:":"Colaboración fluida de foto y video:","Hybrid team ensures":"Un equipo híbrido garantiza una historia visual coherente.","Customized Style:":"Estilo personalizado:","Tailored to match":"Adaptado a tu visión y preferencias únicas.","High-Resolution Digital Gallery:":"Galería digital en alta resolución:","Easily share, download":"Comparte, descarga e imprime tus fotos con facilidad.","Expert Guidance:":"Guía experta:","Support before and during":"Apoyo antes y durante tu boda para lograr las mejores fotos.","Exclusive Wedding Tips PDF:":"PDF exclusivo de consejos de boda:","Includes top advice":"Incluye los mejores consejos para un día perfecto.","Drone Footage Included:":"Tomas con dron incluidas:","Aerial views, weather":"Vistas aéreas, según el clima, para un toque cinematográfico.","Multicultural Wedding Expertise:":"Experiencia en bodas multiculturales:","Experienced in honoring":"Con experiencia en honrar diversas tradiciones culturales.","Cinematic Wedding Video:":"Video de boda cinematográfico:","Professionally edited, high-definition":"Editado profesionalmente en alta definición, con todos los momentos clave.",
"Get in touch":"Contáctanos","First name":"Nombre","Last name":"Apellido","Email":"Correo electrónico","Phone":"Teléfono","Wedding Venue & Location":"Lugar y ubicación de la boda","Wedding Date":"Fecha de la boda","Day":"Día","Month":"Mes","Year":"Año","What service are you interested in?":"¿Qué servicio te interesa?","Choose one":"Elige uno","Photography & Film":"Fotografía y video","Photography":"Fotografía","How did you find about us?":"¿Cómo nos encontraste?","Write a message":"Escribe un mensaje","Submit":"Enviar","Stay connected":"Mantente en contacto","Your email":"Tu correo electrónico","Subscribe":"Suscribirse","El Salvador & London":"El Salvador y Londres",
"PHOTOGRAPHY PORTFOLIO":"PORTAFOLIO DE FOTOGRAFÍA","Our luxury wedding photography":"Nuestro portafolio de fotografía de bodas de lujo muestra la esencia de la elegancia y la sofisticación, capturando momentos atemporales con detalles exquisitos.","We specialize in creating":"Nos especializamos en crear narrativas visuales que reflejan la grandeza y la emoción de tu día especial. Cada fotografía combina visión artística y una artesanía meticulosa, para que tus recuerdos se conserven con belleza y estilo incomparables. Déjanos contar tu historia de amor con imágenes llenas de romance y lujo.","RELAXED:":"RELAJADO:","Embracing a relaxed approach":"Adoptar un enfoque relajado en la fotografía de bodas realza la experiencia de lujo y captura los momentos con elegancia natural. Al crear un ambiente tranquilo y sin prisas, nuestro fotógrafo permite que las parejas disfruten de su día, logrando fotos auténticas y espontáneas.","This stress-free method":"Este método sin estrés no solo muestra la verdadera esencia de la celebración, sino que añade un toque de sofisticación y hace que cada foto cuente una historia sincera.","This blend of relaxed":"Esta fusión de fotografía relajada crea imágenes atemporales que conservan recuerdos preciosos con gracia y estilo, reflejando el ambiente de lujo de tu boda.","EMOTIONAL STORY-TELLING:":"NARRACIÓN EMOTIVA:","An emotional storytelling approach":"Un enfoque de narración emotiva en la fotografía de bodas teje una narrativa poderosa que captura los momentos sinceros que definen el día. Al centrarse en expresiones genuinas e interacciones íntimas, el fotógrafo resalta las emociones que hacen única cada boda.","This method goes beyond":"Este método va más allá de las poses y abraza lo espontáneo y lo natural para contar una historia de amor cautivadora.","Combining modern contemporary":"Al combinar técnicas contemporáneas con un ojo atento a los detalles, el resultado es una colección de imágenes impactantes y profundamente conmovedoras. Cada fotografía se convierte en un recuerdo atesorado que refleja la esencia del camino de la pareja y las emociones compartidas con sus seres queridos.","FILM INSPIRATION":"INSPIRACIÓN CINEMATOGRÁFICA","ARTISTIC VISION":"VISIÓN ARTÍSTICA","Drawing on the world of haute couture":"Inspirado en el mundo de la alta costura, nuestro enfoque destaca las composiciones dramáticas y la atención meticulosa al detalle.","Our photographer utilizes":"Nuestro fotógrafo utiliza técnicas vanguardistas, jugando con la luz, la sombra y ángulos innovadores para crear imágenes llenas de glamour.","This style transforms each moment":"Este estilo convierte cada momento en una foto digna de revista, mostrando a la pareja y a sus invitados en su versión más glamorosa y sofisticada.","The result is a luxurious":"El resultado es una colección lujosa y artística de fotografías que no solo documentan el día de la boda, sino que lo celebran como un evento elegante y atemporal.",
"Films":"Películas","All Videos":"Todos los videos","← All posts":"← Todas las entradas","Read the full article":"Leer el artículo completo","Get in touch today":"Contáctanos hoy","Next:":"Siguiente:"};
const EK=Object.keys(ES).sort((a,b)=>b.length-a.length);
const hit=t=>{const m=t.replace(/\s*\*$/,""),st=m!==t?" *":"",k=EK.find(k=>k.length<=18?m===k:m.startsWith(k));return k?ES[k]+st:null};
function tr(root){if(LANG!=="es"||!root)return;const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),ns=[];while(w.nextNode())ns.push(w.currentNode);ns.forEach(n=>{const t=n.nodeValue.trim();if(!t)return;const v=hit(t);if(v)n.nodeValue=n.nodeValue.replace(t,v)});root.querySelectorAll("[placeholder]").forEach(e=>{const v=hit(e.placeholder);if(v)e.placeholder=v})}
document.documentElement.lang=LANG;
$("#nav").insertAdjacentHTML("beforeend",`<a class="lg" href="${OTHER}" hreflang="${LANG==="es"?"en":"es"}" aria-label="Language">${LANG==="es"?"EN":"ES"}</a>`);
tr($(".top"));tr($("footer"));
route();
$("#sub").onsubmit=e=>{e.preventDefault();location.href=`mailto:hi@davidrj.com?subject=Subscribe&body=${encodeURIComponent("Please add me to your list: "+$("#se").value)}`};
